"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),net=require("node:net"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),cp=require("node:child_process");
const {ServerRegistry}=require("../../kernel-src/http-server.js");
const opts={limits:{connections:20,exchanges:10,requestBytes:1024,responseBytes:1048576,upgrades:2,closeWaiters:2,requestsPerSocket:5,headerPairs:20},headersTimeout:500,requestTimeout:1000,decisionTimeout:100,bodyTimeout:100,writeTimeout:100,finishTimeout:100,keepAliveTimeout:100,upgradeTimeout:80,gracefulTimeout:500};
function fact(...xs){return xs}function connect(port,request){return new Promise((resolve,reject)=>{const s=net.connect(port,"127.0.0.1",()=>s.write(request));const xs=[];s.on("data",x=>xs.push(x));s.on("close",()=>resolve(Buffer.concat(xs)));s.on("error",e=>e.code==="ECONNRESET"?resolve(Buffer.concat(xs)):reject(e));});}
async function setup(hooks={}){let done;const r=new ServerRegistry({...hooks,emit:(_r,x)=>done&&done(x)});const x=await new Promise(resolve=>{done=resolve;r.listen({},1,"127.0.0.1",0,opts,fact)});return{r,id:x[2],port:x[4]};}
async function stop(r,id){await new Promise(resolve=>{r.hooks.emit=(_r,x)=>x[0]===9&&resolve();r.close({},9,id,300,fact)});}
test("absent handler gets bounded timeout rejection and no retained exchange",async()=>{const {r,id,port}=await setup();const data=await connect(port,"GET / HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n");assert.match(data.toString(),/504/);assert.equal(r.snapshot().responses,0);await stop(r,id);});
test("decision timeout rejects and releases",async()=>{const {r,id,port}=await setup({incoming:()=>{}});const data=await connect(port,"GET / HTTP/1.1\r\nHost: x\r\n\r\n");assert.match(data.toString(),/504/);await new Promise(x=>setTimeout(x,20));assert.equal(r.snapshot().responses,0);await stop(r,id);});
test("upgrade preserves nonempty head and transfers exactly once",async()=>{let resolveOffer;const offered=new Promise(r=>resolveOffer=r);const {r,id,port}=await setup({incoming:(_router,_id,raw)=>raw.kind==="upgrade"&&resolveOffer(raw.upgradeId)});const socket=net.connect(port,"127.0.0.1",()=>socket.write("GET /ws HTTP/1.1\r\nHost: x\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\nSec-WebSocket-Version: 13\r\n\r\nHEAD"));const upgradeId=await offered;await new Promise(x=>setTimeout(x,15));const offer=r.claimUpgrade(upgradeId);assert.ok(offer);assert.equal(offer.head.toString(),"HEAD");assert.equal(r.claimUpgrade(upgradeId),null);offer.socket.destroy();await stop(r,id);});
test("offline pinned ws archive loads without ambient dependency",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"schelm-ws-"));try{cp.execFileSync("tar",["-xzf",path.resolve(__dirname,"../../vendor/ws-8.21.1.tgz"),"-C",dir]);const ws=require(path.join(dir,"package"));assert.equal(typeof ws.WebSocketServer,"function");assert.equal(require(path.join(dir,"package/package.json")).version,"8.21.1");}finally{cp.execFileSync("chmod",["-R","u+w",dir]);fs.rmSync(dir,{recursive:true,force:true});}});
