"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),http=require("node:http");
const {SafeIds,Budget,ServerRegistry,MAX_SAFE_ID}=require("../../kernel-src/http-server.js");
const fact=(...xs)=>xs;
const opts={limits:{connections:8,exchanges:8,requestBytes:1024,responseBytes:1024,upgrades:8,closeWaiters:2,requestsPerSocket:8,headerPairs:20},headersTimeout:500,requestTimeout:1000,decisionTimeout:200,bodyTimeout:200,writeTimeout:200,finishTimeout:200,keepAliveTimeout:100,upgradeTimeout:200,gracefulTimeout:500};
const view=text=>{const b=Buffer.from(text);return new DataView(b.buffer,b.byteOffset,b.byteLength)};
const request=port=>new Promise((resolve,reject)=>{const req=http.request({host:"127.0.0.1",port,path:"/",agent:false},res=>{const chunks=[];res.on("data",x=>chunks.push(x));res.on("end",()=>resolve({status:res.statusCode,body:Buffer.concat(chunks).toString()}));});req.on("error",reject);req.end();});
const close=(registry,id)=>new Promise(resolve=>{registry.hooks.emit=(_router,x)=>x[0]===99&&resolve(x);registry.close({},99,id,500,fact)});

for(const name of ["listener","request","body","response","writer","upgrade"]){
  test(`${name} identity allocates MAX_SAFE_INTEGER once then becomes terminal`,()=>{const ids=new SafeIds([name]);ids.setNext(name,MAX_SAFE_ID);assert.deepEqual(ids.allocate([name]),[MAX_SAFE_ID]);assert.equal(ids.peek(name),null);assert.equal(ids.allocate([name]),null);assert.equal(ids.peek(name),null);});
}

test("multi-identity allocation rejects atomically before changing any stream",()=>{const ids=new SafeIds(["request","body","response"]);ids.setNext("request",MAX_SAFE_ID);ids.setNext("body",null);ids.setNext("response",MAX_SAFE_ID);assert.equal(ids.allocate(["request","body","response"]),null);assert.equal(ids.peek("request"),MAX_SAFE_ID);assert.equal(ids.peek("body"),null);assert.equal(ids.peek("response"),MAX_SAFE_ID);});

test("budget last safe reservation succeeds and exhaustion changes no reservation or count",()=>{const budget=new Budget({bytes:3});budget.ids.setNext("default",MAX_SAFE_ID);const id=budget.reserve(7,"bytes",1,3);assert.equal(id,MAX_SAFE_ID);const before=budget.snapshot();assert.equal(budget.reserve(7,"bytes",1,3),0);assert.deepEqual(budget.snapshot(),before);assert.equal(budget.release(id),true);assert.equal(budget.release(id),false);});

test("listener last safe identity binds once; next listen rejects before reservation, server creation, or bind retention",async()=>{let resolveFirst;const replies=[];const registry=new ServerRegistry({emit:(_router,x)=>{replies.push(x);if(x[0]===1)resolveFirst(x)}});registry.ids.setNext("listener",MAX_SAFE_ID);const first=await new Promise(resolve=>{resolveFirst=resolve;registry.listen({},1,"127.0.0.1",0,opts,fact)});assert.equal(first[2],MAX_SAFE_ID);const before=registry.snapshot();registry.listen({},2,"127.0.0.1",0,opts,fact);assert.deepEqual(replies.at(-1),[2,"unsupported",0,"",0]);assert.deepEqual(registry.snapshot(),before);assert.equal(registry.binds.size,0);await close(registry,MAX_SAFE_ID);});

test("request/body/response last safe tuple is offered once; exhausted tuple rejects without map or counter mutation",async()=>{let listening;const facts=[];const registry=new ServerRegistry({emit:(_router,x)=>{facts.push(x);if(x[0]===1)listening(x)},incoming:(router,_listener,raw)=>registry.send(router,2,raw.responseId,200,[],view("ok"),fact)});registry.ids.setNext("request",MAX_SAFE_ID);registry.ids.setNext("body",MAX_SAFE_ID);registry.ids.setNext("response",MAX_SAFE_ID);const opened=await new Promise(resolve=>{listening=resolve;registry.listen({},1,"127.0.0.1",0,opts,fact)});const first=await request(opened[4]);assert.deepEqual(first,{status:200,body:"ok"});while(registry.snapshot().responses)await new Promise(resolve=>setImmediate(resolve));const before={ids:["request","body","response"].map(x=>registry.ids.peek(x)),accepted:registry.listeners.get(opened[2]).accepted,maps:registry.snapshot(),facts:facts.length};const second=await request(opened[4]);assert.equal(second.status,503);assert.deepEqual(["request","body","response"].map(x=>registry.ids.peek(x)),before.ids);assert.equal(registry.listeners.get(opened[2]).accepted,before.accepted);assert.equal(registry.snapshot().bodies,before.maps.bodies);assert.equal(registry.snapshot().responses,before.maps.responses);assert.equal(facts.length,before.facts);await close(registry,opened[2]);});

test("writer last safe identity succeeds; next stream fails before headers or writer retention",()=>{const emitted=[];const registry=new ServerRegistry({emit:(_router,x)=>emitted.push(x)});registry.ids.setNext("writer",MAX_SAFE_ID);let heads=0;const exchange={terminal:false,req:{method:"GET"},res:{headersSent:false,writeHead(){heads++;this.headersSent=true;}},listener:{options:opts}};registry.responses.set(41,exchange);registry.stream({},1,41,200,[],fact);assert.deepEqual(emitted.shift(),[1,"ok",MAX_SAFE_ID]);assert.equal(registry.writers.has(MAX_SAFE_ID),true);const second={terminal:false,req:{method:"GET"},res:{headersSent:false,writeHead(){heads++;this.headersSent=true;}},listener:{options:opts}};registry.responses.set(42,second);const size=registry.writers.size;registry.stream({},2,42,200,[],fact);assert.deepEqual(emitted.shift(),[2,"invalid",0]);assert.equal(heads,1);assert.equal(registry.writers.size,size);assert.equal(second.res.headersSent,false);});

test("upgrade/request last safe pair is offered once; next offer rejects before reservation, retention, timer, or incoming reply",()=>{const incoming=[];const registry=new ServerRegistry({incoming:(_router,_listener,raw)=>incoming.push(raw)});const listener={id:5,closing:null,options:opts,upgrades:new Set()};registry.listeners.set(5,listener);registry.ids.setNext("upgrade",MAX_SAFE_ID);registry.ids.setNext("request",MAX_SAFE_ID);const socket={destroyed:false,end(){},destroy(){this.destroyed=true},once(){}},req={method:"GET",url:"/",httpVersion:"1.1",rawHeaders:[]};registry.offerUpgrade(5,req,socket,Buffer.alloc(0));assert.equal(incoming.length,1);assert.equal(incoming[0].upgradeId,MAX_SAFE_ID);assert.equal(incoming[0].request.id,MAX_SAFE_ID);registry.claimUpgrade(MAX_SAFE_ID);let ended="";const rejectedSocket={destroyed:false,end:x=>{ended=x},destroy(){}};const before=registry.snapshot();registry.offerUpgrade(5,req,rejectedSocket,Buffer.alloc(0));assert.match(ended,/503/);assert.equal(incoming.length,1);assert.equal(listener.upgrades.size,0);assert.deepEqual(registry.snapshot(),before);});
