"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),http=require("node:http"),net=require("node:net");
const {ServerRegistry}=require("../../kernel-src/http-server.js");
const opts={limits:{connections:300,exchanges:200,requestBytes:1048576,responseBytes:8388608,upgrades:16,closeWaiters:8,requestsPerSocket:1000,headerPairs:100},headersTimeout:1000,requestTimeout:2000,decisionTimeout:500,bodyTimeout:500,writeTimeout:2000,finishTimeout:2000,keepAliveTimeout:200,upgradeTimeout:300,gracefulTimeout:2000};
function makeFact(...xs){return xs}
function view(value){const b=Buffer.from(value);return new DataView(b.buffer,b.byteOffset,b.byteLength);}
async function start(onIncoming){let listening;const registry=new ServerRegistry({emit:(_r,value)=>{if(value[0]===1)listening(value);},incoming:(_r,_id,raw,owner)=>onIncoming(registry,raw,owner)});const fact=await new Promise(resolve=>{listening=resolve;registry.listen({},1,"127.0.0.1",0,opts,makeFact)});assert.equal(fact[1],"ok");return{registry,id:fact[2],port:fact[4]};}
function request(port,options={},body){return new Promise((resolve,reject)=>{const req=http.request({host:"127.0.0.1",port,path:"/hello",method:body?"POST":"GET",...options},res=>{const chunks=[];res.on("data",x=>chunks.push(x));res.on("end",()=>resolve({status:res.statusCode,body:Buffer.concat(chunks),headers:res.headers}));});req.on("error",reject);if(body)req.write(body);req.end();});}
async function shutdown(registry,id){await new Promise((resolve,reject)=>{const previous=registry.hooks.emit;const timer=setTimeout(()=>reject(Error("close timeout")),3000);registry.hooks.emit=(_r,x)=>{if(x[0]===999){clearTimeout(timer);resolve(x);}else if(previous)previous(_r,x);};registry.close({},999,id,1000,(...x)=>x);});assert.equal(registry.snapshot().budget.reservations,0);}
test("real request head, duplicate headers, body pull, response finish",async()=>{let resolveDone;const done=new Promise(r=>resolveDone=r);const {registry,id,port}=await start((r,raw)=>{assert.equal(raw.kind,"request");assert.equal(raw.request.target_,"/hello");assert.deepEqual(raw.request.headers_.filter(x=>x.name==="x-pair").map(x=>x.value),["a","b"]);r.readBody({},10,raw.bodyId,1024,(...x)=>x);r.hooks.emit=(_router,fact)=>{if(fact[0]===10&&fact[1]==="chunk"){assert.equal(Buffer.from(fact[3].buffer,fact[3].byteOffset,fact[3].byteLength).toString(),"payload");r.readBody({},11,raw.bodyId,1024,(...x)=>x);}else if(fact[0]===11&&fact[1]==="complete"){r.send({},12,raw.responseId,200,[{name:"content-type",value:"text/plain"}],view("hello"),(...x)=>x);}else if(fact[0]===12){assert.equal(fact[1],"finish");resolveDone();}};});const result=await request(port,{headers:{"x-pair":["a","b"],connection:"close"}},"payload");assert.equal(result.status,200);assert.equal(result.body.toString(),"hello");await done;await shutdown(registry,id);});
test("streaming writer honors physical drain with one pending write",async()=>{let drains=0,writerId=0,offset=0;const payload=Buffer.alloc(4*1024*1024,7);const {registry,id,port}=await start((r,raw)=>{const pump=()=>{if(offset===payload.length){r.end({},22,writerId,(...x)=>x);return;}const chunk=payload.subarray(offset,Math.min(offset+65536,payload.length));offset+=chunk.length;r.write({},21,writerId,new DataView(chunk.buffer,chunk.byteOffset,chunk.byteLength),(...x)=>x);};r.hooks.emit=(_router,f)=>{if(f[0]===20){writerId=f[2];pump();}else if(f[0]===21){if(f[1]==="drained")drains++;else assert.equal(f[1],"accepted");pump();}};r.stream({},20,raw.responseId,200,[],(...x)=>x);});const result=await request(port,{headers:{connection:"close"}});assert.equal(result.body.length,payload.length);assert.ok(drains>0,"real socket must exercise drain");await shutdown(registry,id);});
test("pipelining delivers only first request and closes deterministically",async()=>{let offers=0;const {registry,id,port}=await start((r,raw)=>{offers++;setTimeout(()=>r.send({},30,raw.responseId,200,[],view("one"),(...x)=>x),20);});const raw=await new Promise((resolve,reject)=>{const socket=net.connect(port,"127.0.0.1",()=>socket.write("GET /one HTTP/1.1\r\nHost: x\r\n\r\nGET /two HTTP/1.1\r\nHost: x\r\nConnection: close\r\n\r\n"));const chunks=[];socket.on("data",x=>chunks.push(x));socket.on("close",()=>resolve(Buffer.concat(chunks).toString()));socket.on("error",reject);});assert.equal(offers,1);assert.match(raw,/HTTP\/1\.1 (200|429)/);await shutdown(registry,id);});
test("slowloris headers timeout closes incomplete request",async()=>{const {registry,id,port}=await start(()=>{throw Error("must not offer")});await new Promise((resolve,reject)=>{const socket=net.connect(port,"127.0.0.1",()=>socket.write("GET / HTTP/1.1\r\nHost:"));socket.on("close",resolve);socket.on("error",e=>e.code==="ECONNRESET"?resolve():reject(e));setTimeout(()=>{socket.destroy();resolve();},1800);});await shutdown(registry,id);});
